@startuml async
skinparam maxMessageSize 220

participant Owner

box "Local Network" #LightGray
participant "Target Smart Contract" as LocalBlockchain
end box

box "Public Network" #LightGray
participant "Relayer Smart Contract" as PublicRelayer
participant "Proxy Account" as PublicProxy
participant "Target Smart Contract" as PublicTarget
end box


== Asynchronously ==
box Asynchronously
Owner -> PublicRelayer : Send batch to public network (txData[], sig_user[], batchNonce)
loop i = 0; i <= n times
  PublicRelayer -> PublicRelayer: positionNonce = i
  PublicRelayer -> PublicRelayer: user_address = verify sig_user over (txData[i], batchNonce, positionNonce)
  PublicRelayer -> PublicProxy : Delegate txCall to ProxyAccount(user_address)
  PublicProxy -> PublicTarget : Call target smart contract
  PublicTarget --> PublicProxy : Accept changes
  PublicProxy --> PublicRelayer : Return true
end
PublicRelayer -> PublicRelayer: Save the hash over the executed transactions \n hashes[batchNonce] = hash(txData[])
PublicRelayer -> Owner: emit the event
Owner -> Owner : batchNonce++
end box

@enduml