@startuml

actor Owner
actor Users

' Add an additional frame for Private Network
frame "Local \nBlockchain \nSimulation" as LocalSim {
    ' Add nested deployment of Target SC within LocalSim
    component "Target \nSmart \nContract" as LocalTarget
    ' Show Owner as an actor that hosts LocalSim within PrivateNet frame
}

frame "Public Blockchain Network" as PubNet {
    component "Relayer \nSmart \nContract" as Relayer
    component "Proxy \nSmart \nContract" as Proxy
    component "Target \nSmart \nContract" as Target

}

left to right direction
Users --> LocalTarget : Interact
Users <-[dotted]- LocalTarget : Immediate response

LocalSim <-l- Owner : Hosts

LocalTarget -[dotted]-> Relayer : Batch-send
Relayer --> Proxy : Relay
Proxy --> Target : Call

@enduml