@startuml

actor Owner

actor "User" as User1

' actor "User 2" as User2
skinparam ComponentBackgroundColor #FFFFFF90
!define TRANSPARENT #BFFFBF

frame "Server" as Server {
    ' Add an additional frame for Private Network
    frame "Local \nBlockchain \nSimulation" as LocalSim #LightYellow {
        ' Add nested deployment of Target SC within LocalSim
        component "Target \nSmart \nContract" as LocalTarget
        ' Show Owner as an actor that hosts LocalSim within PrivateNet frame
    }
}


frame "Public Blockchain Network" as PubNet #LightGreen {
    component "Relayer \nSmart \nContract" as Relayer
    component "Target \nSmart \nContract" as Target 
}


left to right direction
User1 -down-> LocalTarget : Interact
User1 <-[dotted]- LocalTarget : Immediate response

' User2 -> LocalTarget : Interact
' User2 <-[dotted]- LocalTarget : Immediate response

Server <-l- Owner : Hosts

Server --> Relayer : Batch-send

Relayer --> Target : Relay
' Relayer --> Target : Relay

@enduml