@startuml system
skinparam maxMessageSize 220

participant User
participant Owner

box "Local Network" #LightGray
participant "Target Smart Contract" as LocalBlockchain
end box

box "Public Network" #LightGray
participant "Relayer Smart Contract" as PublicRelayer
end box


User -> Owner : Initiate a request
note left : Has private key
Owner -> User : (batchNonce, positionNonce)
' User -> User : Generate (txData)

User -> Owner : txData
User -> Owner : sig_user = sign (txData, batchNonce, positionNonce)

note right : Has private key

Owner -> LocalBlockchain : send (txData)
LocalBlockchain -> Owner : Update the state & emit events
Owner -> User : immediate feedback \n\nsig_owner = sign (txData, batchNonce, positionNonce, sendTimestamp)


Owner -> Owner : Save to a batch \n positionNonce++


== Asynchronously ==
box Asynchronously
Owner -> PublicRelayer : Send batch to public network \n\nrelayTransactions (txData[], sig_user[], batchNonce)
Owner -> Owner : batchNonce++
end box

@endumld